name: "🐛 Bug Report"
description: "Create a report to help us improve our community workflows"
title: "🐛 Bug: "
labels: ["🐛 Bug", "Status: Triage"]

body:
- type: textarea
  attributes:
    label: "Describe the bug"
    description: "A clear and concise description of what the bug is"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Steps To Reproduce"
    description: "Steps to reproduce the behavior"
    placeholder: |
      1. Go to'...'
      2. Click on'...'
      3. Scroll down to'...'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: "Expected Behavior"
    description: "A clear and concise description of what you expected to happen"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Screenshots"
    description: |
      If applicable, add screenshots to help explain your problem

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
  validations:
    required: false    
- type: textarea
  attributes:
    label: "Device Information [optional]"
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Browser**: chrome
        - **version**: 22
    value: |
        - OS:
        - Browser:
        - version:
    render: markdown
  validations:
    required: false
- type: dropdown
  attributes:
    label: "Are you working on this issue?"
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true
