name: Validate Ambassadors JSON

on:
  push:
    paths:
      - 'programs/ambassadors/ambassadors.json'
  pull_request:
    paths:
      - 'programs/ambassadors/ambassadors.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  

    - name: Install dependencies
      run: npm install
      working-directory: ./programs/ambassadors

    - name: Validate ambassadors.json
      run: node ../utils/validate-ambassadors.js
      working-directory: ./programs/ambassadors
